// @ts-check

import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import {
  CORE_STRENGTHS,
  EDUCATION,
  EMPLOYMENT,
  LANGUAGES,
  OVERVIEW,
  PERSON,
  TECHNOLOGIES,
  TECHNOLOGY_INTERESTS,
} from "../js/resume.js"
import { SITE_URL } from "../js/routes.js"

const OUTPUT_PUBLIC = "./public/llms.txt"

/** @type {readonly string[]} */
const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
]

/**
 * Format an ISO year-month ("2024-01") as "January 2024".
 *
 * @param {string} iso
 * @returns {string}
 */
const formatDate = (iso) => {
  const [year, month] = iso.split("-")
  const monthName = MONTHS[Number(month) - 1]
  return `${monthName} ${year}`
}

/**
 * Format an employment date range for prose.
 *
 * @param {string} startDate
 * @param {string | undefined} endDate
 * @returns {string}
 */
const formatRange = (startDate, endDate) =>
  `${formatDate(startDate)} – ${endDate ? formatDate(endDate) : "present"}`

/**
 * Render a bullet list from string items.
 *
 * @param {string[]} items
 * @returns {string}
 */
const bulletList = (items) => items.map((item) => `- ${item}`).join("\n")

/** @type {Record<string, string>} */
const SOCIAL_LABELS = {
  "bsky.app": "Bluesky",
  "github.com": "GitHub",
  "linkedin.com": "LinkedIn",
}

/**
 * Load version metadata generated by the rev script.
 *
 * @returns {Promise<Record<string, string>>}
 */
async function loadVersion() {
  const scriptDir = path.dirname(fileURLToPath(import.meta.url))
  const versionPath = path.resolve(scriptDir, "../version.json")
  try {
    return JSON.parse(await fs.readFile(versionPath, "utf8"))
  } catch {
    return {}
  }
}

/** @type {{ heading: string; body: string }[]} */
const LEGAL_NOTICES = [
  {
    heading: "Datenschutzerklärung (Privacy)",
    body: `SSL-Verschlüsselung: Diese Seite nutzt aus Gründen der Sicherheit und zum Schutz der Übertragung vertraulicher Inhalte, wie zum Beispiel der Anfragen, die Sie an uns als Seitenbetreiber senden, eine SSL-Verschlüsselung. Eine verschlüsselte Verbindung erkennen Sie daran, dass die Adresszeile des Browsers und/oder an dem Schloss-Symbol in Ihrer Browserzeile. Wenn die SSL Verschlüsselung aktiviert ist, können die Daten, die Sie an uns übermitteln, nicht von Dritten mitgelesen werden.

Datenschutz: Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung. Die Nutzung unserer Webseite ist in der Regel ohne Angabe personenbezogener Daten möglich. Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies, soweit möglich, stets auf freiwilliger Basis. Diese Daten werden ohne Ihre ausdrückliche Zustimmung nicht an Dritte weitergegeben. Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.`,
  },
  {
    heading: "Urheberrecht (Copyright)",
    body: `Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.`,
  },
  {
    heading: "Haftungsausschluss (Disclaimer)",
    body: `Haftung für Inhalte: Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.`,
  },
]

/**
 * Render the employment history section.
 *
 * @returns {string}
 */
const employmentSection = () => {
  const blocks = EMPLOYMENT.map((job) => {
    const lines = [
      `### ${job.organization}`,
      "",
      `- **Role:** ${job.role}`,
      `- **Dates:** ${formatRange(job.startDate, job.endDate)}`,
      "",
      "**Main activities**",
      "",
      bulletList(job.activities),
      "",
      "**Responsibilities**",
      "",
      job.description,
    ]

    return lines.join("\n")
  })

  return ["## Employment History", "", blocks.join("\n\n")].join("\n")
}

/**
 * Render the personal skills section.
 *
 * @returns {string}
 */
const skillsSection = () => {
  const strengths = CORE_STRENGTHS.map(
    (strength) => `### ${strength.title}\n\n${strength.description}`,
  ).join("\n\n")

  const languages = bulletList(
    LANGUAGES.map((lang) => `${lang.name} — ${lang.proficiency}`),
  )

  return [
    "## Personal Skills and Competences",
    "",
    strengths,
    "",
    "### Languages",
    "",
    languages,
    "",
    "### Technology Interests",
    "",
    TECHNOLOGY_INTERESTS,
  ].join("\n")
}

/**
 * Render the imprint section with version metadata.
 *
 * @param {Record<string, string>} version
 * @returns {string}
 */
const imprintSection = (version) => {
  const versionLines = [
    `- **Version:** ${version.version || "(see website)"}`,
    `- **Last update:** ${version.update || "(see website)"}`,
    `- **Commit:** ${version.short || "(see website)"}`,
    `- **Commit count:** ${version.count || "(see website)"}`,
  ]

  return [
    "## Imprint",
    "",
    "Impressum / Imprint",
    "",
    "Angaben gemäß § 5 TMG:",
    "",
    `- **Name:** ${PERSON.name}`,
    "- **Business:** freie Softwareentwicklung",
    `- **Address:** ${PERSON.address.streetAddress}, ${PERSON.address.postalCode} ${PERSON.address.addressLocality}, Germany`,
    `- **Phone:** ${PERSON.telephone}`,
    `- **Email:** ${PERSON.email}`,
    "",
    "A PDF copy of the CV is available for download from the website.",
    "",
    "Semantic information:",
    "",
    ...versionLines,
  ].join("\n")
}

/**
 * Build-step entry point.
 *
 * @returns {Promise<void>}
 */
async function main() {
  const version = await loadVersion()

  const header = `# Schedler.pro | Alexander Schedler: Internet application engineering, development and management.

> Source: [schedler.pro](${SITE_URL}/)
> This file is auto-generated from site content to provide LLM-accessible information.

## Overview
${OVERVIEW}`

  const about = [
    "## About",
    "",
    `- **Name:** ${PERSON.name}`,
    `- **Location:** ${PERSON.homeLocation.name}`,
    "",
    PERSON.description,
  ].join("\n")

  const contact = [
    "## Contact Information",
    "",
    `- **Name:** ${PERSON.name}`,
    `- **Email:** ${PERSON.email}`,
    `- **Phone:** ${PERSON.telephone}`,
    ...PERSON.sameAs.map((url) => {
      const host = new URL(url).hostname.replace(/^www\./, "")
      const label = SOCIAL_LABELS[host] || host
      return `- **${label}:** ${url}`
    }),
  ].join("\n")

  const careerOverview = [
    "## Career Overview",
    "",
    "Companies, newest first:",
    "",
    bulletList(EMPLOYMENT.map((job) => `${job.organization} — ${job.role}`)),
  ].join("\n")

  const education = [
    "## Education",
    "",
    `- **Institution:** ${EDUCATION.schools.join(" and ")}`,
    `- **Degree:** ${EDUCATION.degree}`,
    `- **Dates:** ${formatRange(EDUCATION.startDate, EDUCATION.endDate)}`,
    "",
    "**Subjects**",
    "",
    bulletList(EDUCATION.subjects),
  ].join("\n")

  const technologies = [
    "## Technologies",
    "",
    bulletList(
      TECHNOLOGIES.map(
        (tech) => `${tech.name} — ${tech.level} — ${tech.years}`,
      ),
    ),
  ].join("\n")

  const legal = [
    "## Legal Notices",
    "",
    LEGAL_NOTICES.map(
      (notice) => `### ${notice.heading}\n\n${notice.body}`,
    ).join("\n\n"),
  ].join("\n")

  const sections = [
    header,
    about,
    contact,
    careerOverview,
    employmentSection(),
    education,
    skillsSection(),
    technologies,
    imprintSection(version),
    legal,
  ]

  const output = `${sections.join("\n\n")}\n`

  await fs.writeFile(OUTPUT_PUBLIC, output)
  console.log(`✅ Generated ${OUTPUT_PUBLIC}`)
}

await main()
