// @ts-check

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DESKTOP_DIR = "./src/txt/desktop";
const OUTPUT_PUBLIC = "./public/llms.txt";

/** Unicode decorative characters (box-drawing, block elements, geometric shapes) */
const DECORATIVE_RE = /[\u2500-\u259F\u25A0-\u25FF]/g;

/** Clusters of ASCII art characters (2 or more consecutive art chars) */
const ART_CLUSTER_RE = /[*#●^~○]{2,}/g;

/**
 * @typedef {{ file: string; heading: string; level: number }} SectionConfig
 */

/** @type {SectionConfig[]} */
const SECTIONS = [
  { file: "start.txt", heading: "About", level: 2 },
  { file: "contact1.txt", heading: "Contact Information", level: 2 },
  { file: "Freelance.txt", heading: "Freelance Work", level: 2 },
  { file: "jobs.txt", heading: "Career Overview", level: 2 },
  { file: "jobs-certania.txt", heading: "CERTANIA Holding GmbH", level: 3 },
  { file: "jobs-jd.txt", heading: "Johner Institut GmbH", level: 3 },
  { file: "jobs-man.txt", heading: "MAN Energy Solutions SE", level: 3 },
  { file: "jobs-iob.txt", heading: "Internet of Blah / PURR", level: 3 },
  { file: "jobs-txn.txt", heading: "ThinxNet GmbH", level: 3 },
  { file: "jobs-no.txt", heading: "natureOffice GmbH", level: 3 },
  { file: "jobs-dyno.txt", heading: "Dynomedia GmbH", level: 3 },
  { file: "jobs-kigg.txt", heading: "KIGG GmbH", level: 3 },
  { file: "education.txt", heading: "Education", level: 2 },
  {
    file: "skills.txt",
    heading: "Personal Skills and Competences",
    level: 2,
  },
  { file: "technologies.txt", heading: "Technologies", level: 2 },
  { file: "impressum.txt", heading: "Imprint", level: 2 },
  { file: "impressum2.txt", heading: "Legal Notices", level: 2 },
];

/**
 * Load version metadata generated by the rev script.
 *
 * @returns {Promise<Record<string, string>>}
 */
async function loadVersion() {
  const scriptDir = path.dirname(fileURLToPath(import.meta.url));
  const versionPath = path.resolve(scriptDir, "../version.json");
  try {
    return JSON.parse(await fs.readFile(versionPath, "utf8"));
  } catch {
    return {};
  }
}

/**
 * Check whether a word looks like real text rather than ASCII art.
 * A real word must contain at least 2 alphabetic characters drawn
 * from at least 2 distinct letters.
 *
 * @param {string} word
 * @returns {boolean}
 */
function isRealWord(word) {
  const alpha = word.replace(/[^a-zA-ZäöüÄÖÜß]/g, "");
  if (alpha.length < 2) return false;
  return new Set(alpha.toLowerCase()).size >= 2;
}

/**
 * Detect whether a single-word segment is likely logo / ASCII-art noise.
 *
 * Two heuristics are applied:
 *  1. The word (letters only) is a substring of the section heading –
 *     i.e. it is the company name echoed in the logo.
 *  2. The word consists of a short character pattern repeated multiple
 *     times (e.g. "certaniacertaniacert").
 *
 * @param {string} segment
 * @param {string} headingAlpha  heading with non-alpha chars removed, lowercased
 * @returns {boolean}
 */
function isLogoNoise(segment, headingAlpha) {
  const words = segment.trim().split(/\s+/);
  if (words.length > 1) return false;

  const alpha = words[0]
    .replace(/[^a-zA-ZäöüÄÖÜß]/g, "")
    .toLowerCase();

  // Single word that is a substring of the section heading
  if (
    alpha.length >= 3 &&
    headingAlpha.length > 0 &&
    headingAlpha.includes(alpha)
  ) {
    return true;
  }

  // Long word built from a repeating pattern (exact or partial)
  if (alpha.length >= 10) {
    for (let len = 3; len <= Math.floor(alpha.length / 2); len++) {
      const pattern = alpha.slice(0, len);
      const repeated = pattern
        .repeat(Math.ceil(alpha.length / len))
        .slice(0, alpha.length);
      if (alpha === repeated) return true;
    }
    // Also catch partial repeats: any 4+ letter substring appearing twice
    for (let len = 4; len <= Math.floor(alpha.length / 2); len++) {
      for (let start = 0; start <= alpha.length - len * 2; start++) {
        const sub = alpha.slice(start, start + len);
        if (alpha.indexOf(sub, start + len) !== -1) return true;
      }
    }
  }

  return false;
}

/**
 * Extract meaningful text lines from a single ASCII-art file.
 *
 * @param {string} content   raw file content
 * @param {string} heading   section heading (used to filter logo noise)
 * @returns {string[]}
 */
function extractText(content, heading) {
  const headingAlpha = heading.toLowerCase().replace(/[^a-zäöüß]/g, "");
  const lines = content.split("\n");
  /** @type {string[]} */
  const result = [];

  for (const line of lines) {
    // 1. Replace Unicode decorative characters with spaces
    const cleaned = line.replace(DECORATIVE_RE, " ");

    // 2. Split into segments by runs of 3+ whitespace
    const segments = cleaned
      .split(/\s{3,}/)
      .map((s) => s.trim())
      .filter(Boolean);

    // 3. Keep only segments that contain real words, then clean them up
    const textSegments = segments
      .filter((seg) => {
        const words = seg.match(/[a-zA-ZäöüÄÖÜß]{2,}/g) || [];
        return words.some(isRealWord);
      })
      .map((seg) =>
        seg
          .replace(ART_CLUSTER_RE, " ") // strip art-character clusters
          .replace(/^\.{2,}\s*/, "") // leading decorative dots
          .replace(/\s*\.{2,}$/, "") // trailing decorative dots
          .replace(/\s+/g, " ")
          .trim(),
      )
      .filter((seg) => {
        if (!seg || seg.length < 2) return false;
        const words = seg.match(/[a-zA-ZäöüÄÖÜß]{2,}/g) || [];
        if (!words.some(isRealWord)) return false;
        if (isLogoNoise(seg, headingAlpha)) return false;
        return true;
      });

    if (textSegments.length > 0) {
      result.push(textSegments.join(" | "));
    }
  }

  // Deduplicate consecutive identical lines
  const deduped = result.filter(
    (line, i) => i === 0 || line !== result[i - 1],
  );

  // Drop lines that just echo the section heading
  const headingNorm = heading.toLowerCase().replace(/[^a-z0-9]/g, "");
  return deduped.filter((line) => {
    const lineNorm = line.toLowerCase().replace(/[^a-z0-9]/g, "");
    if (lineNorm === headingNorm) return false;
    // Filter UI navigation fragments
    if (/^<-\s/.test(line.trim())) return false;
    return true;
  });
}

/**
 * Build-step entry point.
 *
 * @returns {Promise<void>}
 */
async function main() {
  const version = await loadVersion();

  const header = `# Schedler.co | Alexander Schedler: Internet application engineering, development and management.

> Source: [schedler.co](https://schedler.co/)
> This file is auto-generated from site content to provide LLM-accessible information.

## Overview
This site serves as a professional portfolio and curriculum vitae for Alexander Schedler, showcasing expertise in internet application engineering, development, and management. Below you will find detailed information about his professional background, skills, and experience.`;

  /** @type {string[]} */
  const outputParts = [header];
  let needsEmploymentHeader = true;

  for (const { file, heading, level } of SECTIONS) {
    const filePath = path.join(DESKTOP_DIR, file);
    try {
      let content = await fs.readFile(filePath, "utf-8");

      // Fill in template placeholders with version metadata
      content = content.replace(
        /\{\{(\w+)-*\}\}/g,
        (_match, /** @type {string} */ key) =>
          version[key] || "(see website)",
      );

      const textLines = extractText(content, heading);

      if (textLines.length > 0) {
        // Insert an "Employment History" header before the first job section
        if (needsEmploymentHeader && level === 3) {
          outputParts.push("## Employment History");
          needsEmploymentHeader = false;
        }

        const prefix = "#".repeat(level);
        outputParts.push(
          `${prefix} ${heading}\n\n${textLines.join("\n")}`,
        );
      }
    } catch (err) {
      console.warn(
        `Warning: Could not read ${filePath}: ${/** @type {Error} */ (err).message}`,
      );
    }
  }

  const output = `${outputParts.join("\n\n")}\n`;

  await fs.writeFile(OUTPUT_PUBLIC, output);
  console.log(`✅ Generated ${OUTPUT_PUBLIC}`);
}

await main();
