const start = `                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                           ╔══════════════════════════════════════════════════════════════╗                                          
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║    <strong>Alexander Schedler</strong>                                        ║░░                                        
                                           ║    District of Augsburg, Germany                             ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║        Internet application <mark>engineering</mark>,                     ║░░                                        
                                           ║        <mark>development</mark> and <mark>management</mark>.                           ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║        <mark>Javascript</mark> (Frontend and Backend),                    ║░░                                        
                                           ║        HTML, CSS, Node, GraphQL, CouchDB                     ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ║                                                              ║░░                                        
                                           ╚══════════════════════════════════════════════════════════════╝░░                                        
                                             ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                                        
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     
                                                                                                                                                     `
//
const education = `
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                          SAE Institute Munich, Germany and                               ║
║                                                                          Middlesex University London, UK                                 ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                           <mark>Bachelor of Arts Multimedia</mark>                                    ║
║                                                                          -----------------------------                                   ║
║                                                                             August 2001 - May 2004                                       ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                          Contemporary issues and research                                ║
║                                                                          Business management, marketing and legal issues                 ║
║                                                                          Psychology, team management and storyboarding                   ║
║                                                                          Multimedia and education                                        ║
║                                                                          Multimedia and Online Production                                ║
║                                                                          Graphic design                                                  ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
║                                                                                                                                          ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝`
//
const oneToThree = `
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                           ╔══════════════════════════════════════════════════════════════╗                                                                                                                                                                                                                                                                                 
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║    Alexander Schedler                                        ║░░                                                                                                                                                                                                                                                                               
                                           ║    District of Augsburg, Germany                             ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║        Internet application engineering,                     ║░░                                                                                                                                                                                                                                                                               
                                           ║        development and management.                           ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║        Javascript (Frontend and Backend),                    ║░░                                                                                                                                                                                                                                                                               
                                           ║        HTML, CSS, Node, GraphQL, CouchDB                     ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                                                                                                                                                                               
                                           ║                                                              ║░░                                                                                                                           ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ 
                                           ║                                                              ║░░                                                                                                                          ╳                                                                                                                                                   ╳
                                           ║                                                              ║░░                                                                                                                          ╳                                                                                                                                                   ╳
                                           ╚══════════════════════════════════════════════════════════════╝░░                                                                                                                          ╳                                                                                                                                                   ╳
                                             ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                                                                                                                          ╳                                                                                                                                                   ╳
                                                                           │                                                                                                                                                           ╳                                                                                                                                                   ╳
                                                                           │                                                                                                                                                           ╳                                                                                                                                                   ╳
                                                                           │                                                                                                                                                           ╳                                                                                                                                                   ╳
                                                                           │                                                                                                                                                           ╳                                                                                                                                                   ╳
                                                                           │                                                                                                                                                           ╳                                                                                                                                                   ╳
                                                                           │                                                                                                                                                           ╳                                                                                                                                                   ╳
                                                                           │                                                                                                                                                           ╳                                          ╔══════════════════════════════════════════════════════════════╗                                         ╳
                                                                           │                                                                                                                                                           ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║    Alexander Schedler                                        ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║    freelance software developer                              ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║        Currlently I am working salaried for MAN              ║░░                                       ╳
                                                                           │                                                                                                                                                           ╳                                          ║        Energy Solutions. I also do freelance work with a     ║░░                                       ╳
                                                                           │                                                                                                                                                   ┌─────────────────────────────────────────────────┼║        key focus on enterprize or b2b web application        ║░░                                       ╳
                                                                           │                                                                                                                                                   │       ╳                                          ║        development and management as well as JavaScript      ║░░                                       ╳
                                                                           │                                                                                                                                                   │       ╳                                          ║        and CouchDB consulting.                               ║░░                                       ╳
                                                                           │                                                                                                                                                   │       ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                                                                                                                                   │       ╳                                          ║        Need my help? Just write me.                          ║░░                                       ╳
                                                                           │                                 ╔══════════════════════════════════════════════════════════════╗                                                  │       ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                 ║                                                              ║░░                                                │       ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                 ║                                                              ║░░                                                │       ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                 ║                                                              ║░░                                                │       ╳                                          ║                                                              ║░░                                       ╳
                                                                           │                                 ║                                                              ║░░                                                │       ╳                                          ╚══════════════════════════════════════════════════════════════╝░░                                       ╳
                                                                           │                                 ║    Alexander Schedler                                        ║░░                                                │       ╳                                            ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                                       ╳
                                                                           │                                 ║    District of Augsburg, Germany                             ║░░                                                │       ╳                                                                                                                                                   ╳
                                                                           │                                 ║                                                              ║░░                                                │       ╳                                                                                                                                                   ╳
                                                                           │                                 ║        Want to get in touch?                                 ║░░                                                │       ╳                                                                                                                                                   ╳
                                                                           │                                 ║        Just write me an Email alex@schedler.co or call me    ║░░                                                │       ╳                                                                                                                                                   ╳
                                                                           └────────────────────────────────┼║        +49 171 4 123 929 and follow me on twitter            ║──────────────────────────────────────────────────┘       ╳                                                                                                                                                   ╳
                                                                                                             ║        @kulturpessimist and star my work on Github           ║░░                                                        ╳                                                                                                                                                   ╳
                                                                                                             ║        /kulturpessimist or connect me on LinkedIn            ║░░                                                        ╳                                                                                                                                                   ╳
                                                                                                             ║        /alexanderschedler or Xing /Alex_Schedler             ║░░                                                        ╳                                                                                                                                                   ╳
                                                                                                             ║                                                              ║░░                                                         ╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳╳ 
                                                                                                             ║                                                              ║░░                                                                                                                                                                                                             
                                                                                                             ║                                                              ║░░                                                                                                                                                                                                             
                                                                                                             ║                                                              ║░░                                                                                                                                                                                                             
                                                                                                             ║                                                              ║░░                                                                                                                                                                                                             
                                                                                                             ╚══════════════════════════════════════════════════════════════╝░░                                                                                                                                                                                                             
                                                                                                               ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            `
const pages = [start, education, oneToThree]

export default pages
